//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.20 at 11:33:08 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.soap.web.com/")
package com.example.howtodoinjava.schemas.school;
